security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:    ^/backend/login$
            anonymous:  ~
        main:
            pattern: ^/backend
            form_login:
                check_path: /backend/login_check
                login_path: /backend/login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /backend/logout
                target: /

    access_control:
        - { path: ^/backend/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/admin/, role: ROLE_ADMIN }