<?php

namespace DataBundle\Repository;

/**
 * PageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithKeyword($keyword)
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->where('p.content like :word')
            ->setParameter('word', '%'.$keyword.'%')
        ;

        $qb->setMaxResults(10);

        return $qb->getQuery()->getresult();
    }
}
