<?php

namespace DataBundle\Repository;

/**
 * PartialRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartialRepository extends \Doctrine\ORM\EntityRepository
{
}
